### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'createTreeWalker')

### ISSUE THREAD

**Issue by SamuelWei** [asamuzaK/domSelector#37]
I use Vue 2 + Vitest + JsDom for running component tests.
Since JsDom changed to you package my tests are failing.

I'm currently unable to create a minimal repo to demonstrate this issue.

However I tried to debug it and it comes down to this code section.

```js
let parent = node;
while (parent) {
  if (parent.parentNode) {
    parent = parent.parentNode;
  } else {
    break;
  }
}
document = parent.ownerDocument;
root = parent;
```
https://github.com/asamuzaK/domSelector/blame/c0b90ba4dcf7a58c3aa3e852e476c5707b398356/src/js/matcher.js#L147C11-L156C25

After the `closest` method is called on an HTML Element this section is executed. By the end `document ` is `null ` and therefore throws an error here:

```js
const walker = document.createTreeWalker(root, filter);
```
https://github.com/asamuzaK/domSelector/blame/c0b90ba4dcf7a58c3aa3e852e476c5707b398356/src/js/matcher.js#L173

I looked into the state of the while loop before the error was thrown:
- Button
- Div
- Body
- Html
- Doument -> break

The loop break if parent is Document, however on Document there is no `ownerDocument` (https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument), resulting in `document` beeing `null` and thus causing the issue when running  `document.createTreeWalker`

@asamuzaK Do you have any tests implemented to tests this part of your if-else-statement for the `case ELEMENT_NODE`?
If so, where do I find it, so I can try to demonstrate the issue. If not, could you please make sure the while loop is working as intended. Thanks!

**Comment by asamuzaK** [comment]
Thanks for your contribution.

https://github.com/jsdom/jsdom/issues/3659#issuecomment-1883505676
I can see that, an error is thrown while constructing an instance of the Matcher.

But, I can not confirm.
Below is what I got, neither throws.

```js
const domstr = '<div><button id="test"></button></div>';
document.body.innerHTML = domstr;
const node = document.getElementById('test');
const res = node.closest('.foo');

assert.isNull(res, 'result');
assert.deepEqual(node.ownerDocument, document, 'ownerDocument');
assert.isTrue(typeof document.createTreeWalker === 'function', 'TreeWalker');
assert.deepEqual(document.defaultView, window, 'window');
```

```js
const domstr =
  '<html><body><div><button id="test"></button></div></body></html>';
const doc = DOMParser().parseFromString(domstr, 'text/html');
const node = doc.getElementById('test');
const res = node.closest('.foo');

assert.isNull(res, 'result');
assert.deepEqual(node.ownerDocument, doc, 'ownerDocument');
assert.isTrue(typeof doc.createTreeWalker === 'function', 'TreeWalker');
assert.isNull(doc.defaultView, 'defaultView');
assert.deepEqual(document.defaultView, window, 'window');
```

**Comment by asamuzaK** [comment]
> Do you have any tests implemented to tests this part of your if-else-statement for the case ELEMENT_NODE?

I've made some major changes internally, and in the process of rewriting it.
https://github.com/asamuzaK/domSelector/pull/36/commits/dc42607163c40c52bd32da5d1fe9e9e05dbee013

**Comment by asamuzaK** [comment]
Test log:
```
const doc = new DOMParser().parseFromString('<html></html>', 'text/html');
doc.defaultView; // null
doc.ownerDocument; // null
doc.createTreeWalker; // function
doc.body; // <body>
doc.createElement; // function

const node = document.createElement('div');
node.ownerDocument === document; // true
document.contains(node); // false
doc.body.append(node);
node.ownerDocument === document; // false, ownerDocument changed
node.ownerDocument === doc; // true
doc.contains(node); // true

// detach html from doc
const html = doc.removeChild(doc.documentElement);
doc.contains(node); // false
html.contains(node); // true;

let parent = node;
while (parent) {
  if (parent.parentNode) {
    parent = parent.parentNode;
  } else {
    break;
  }
}
parent === doc;	// false
parent === html; // true
parent.ownerDocument === doc // true
```

I can't imagine the case that some node is **not** contained by a Document but **is** a decsendant of a Document...

```js
if (node.ownerDocument.contains(node)) {
  document = node.ownerDocument;
  root = node.ownerDocument;
} else {
  let parent = node;
  while (parent) {
    if (parent.parentNode) {
      parent = parent.parentNode;
    } else {
      break;
    }
  }
  if (parent.nodeType === DOCUMENT_NODE) { // should never match...
    document = parent;
  } else {
    document = parent.ownerDocument;
  }
  root = parent;
}
```

**Comment by asamuzaK** [comment]
Closing this for now.
